### ISSUE TITLE
module 'pointnet2_cuda' has no attribute 'knn_wrapper'

### ISSUE THREAD

**Issue by rasrab1992** [IMRL/HPPLO-Net#3]
Hello. Thank you for your great work. During running your code, I faced with this error. It seems that pointnet2_utils.py doesn't have knn_wrapper. Could you please modify your code or help me debug it?

Thanks.

`Traceback (most recent call last):
  File "/opt/conda/envs/HPPLO/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/HPPLO/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 322, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 136, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/root/.vscode-server/extensions/ms-python.debugpy-2024.8.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/Projects/codes/TransLO/HPPLO-Net/trainercom.py", line 226, in <module>
    proceed_one_epoch(epoch, timeflag, parse.trainloader, model, optimizer, criterion, needloss=True)
  File "/home/Projects/codes/TransLO/HPPLO-Net/tools/trainer.py", line 363, in proceed_one_epoch
    batchoutput, poseoutput, layernum = proceed_fun(epoch, i, timeflag, dataseq, model, optimizer, criterion, needgtloss, needloss, nowcontinlen)
  File "/home/Projects/codes/TransLO/HPPLO-Net/tools/trainer.py", line 234, in proceed_one_voxelvlad
    netout = model(list(netinput), showtestloss or needloss)
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/voxelnetvlad.py", line 47, in forward
    nowpoints[:, :, 3:], lastpoints[:, :, 3:], needmul, idx1, idx2)
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/pointPWC/pointPWC.py", line 357, in forward
    flows, fps_pc1_idxs, fps_pc2_idxs, pc1, pc2, R, T = self.pointpwc(xyz1, xyz2, color1, color2, idx1, idx2)
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/pointPWC/pointPWC.py", line 232, in forward
    R3, T3, _ = self.svd(pc1_l3.transpose(1, 2), torch.cat((pc2_l0, color2), dim=1).transpose(1, 2), feat2_l0_1, flow3.transpose(1, 2), weight3)
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/SVDnet.py", line 39, in forward
    R, T = self.svdcore(src, tag, feat2_l0_1, flow, weight)  
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/SVDnet.py", line 79, in forward
    tgtnor = self.estimate_normal(tgt, oldtgt, oldtgtnor, feat2_l0_1.permute(0, 2, 1))
  File "/opt/conda/envs/HPPLO/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/pointPWC/pointconv_util_fastknn.py", line 664, in forward
    _, idx1 = pointnet2_utils.knn(4, des_pc.contiguous(), pc2_l0.contiguous())  #des_pc find knn in pc2_l0  (b, 512,8)
  File "/home/Projects/codes/TransLO/HPPLO-Net/model/voxelnetvlad/flownet3d/pointnet2_utils.py", line 99, in forward
    pointnet2.knn_wrapper(B, N, m, k, unknown, known, dist2, idx)
AttributeError: module 'pointnet2_cuda' has no attribute 'knn_wrapper'`

**Comment by judemihoo** [comment]
I also encountered this issue: module 'pointnet2_cuda' has no attribute 'knn_wrapper

**Comment by xodus777** [comment]
Hello, I've encounterd the same error, and found out that the pointnet2 implemented in flownet3D_pytorch implementation includes the implementation of `knn_wrapper`.

For those who have same problem, I recommend you to try to intall the following library:
https://github.com/hyangwinter/flownet3d_pytorch
